version: 2.1
workflows:
  build-and-run:
    jobs:
      - build
jobs:
  build:
    steps:
      - run: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          command: |
            ./tools/download-templates.sh
            export DOCKER_BUILDKIT=1
            sudo -E docker build . -t DCAN-LABS/nhp-abcd-bids-pipeline-synth:docker-build -q
            sudo docker system prune -f
          no_output_timeout: 1h
